AutomataOnRails/config/routes.rb
Rails.application.routes.draw do
  root 'inicio#index'

  resources :operations

  resources :samples

end

AutomataOnRails/app/models/operation.rb
class Operation < ActiveRecord::Base
	validates :sample1, presence: true, length: { minimum: 1 }
	validates :sample2, presence: true, length: { minimum: 1 }
	validates :kleene, presence: true
end

AutomataOnRails/app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]

  # GET /operations
  # GET /operations.json
  def index
    @operations = Operation.all
    @samples = Sample.all
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
    @elemento1 = Sample.find(@operation.sample1)
    @elemento2 = Sample.find(@operation.sample2)
    @union = unir(@elemento1.lenguaje, @elemento2.lenguaje)
    @inter = interseccion(@elemento1.lenguaje, @elemento2.lenguaje)
    @concat1 = concatenar(@elemento1.lenguaje, @elemento2.lenguaje)
    @concat2 = concatenar(@elemento2.lenguaje, @elemento1.lenguaje)
    @estrella1 = estrella(@elemento1.lenguaje, @operation.kleene)
    @tamE1 = cuenta(@estrella1)
    @estrella2 = estrella(@elemento2.lenguaje, @operation.kleene)
    @tamE2 = cuenta(@estrella2)
    @resta1 = restar(@elemento1.lenguaje, @elemento2.lenguaje)
    @resta2 = restar(@elemento2.lenguaje, @elemento1.lenguaje)
  end

  # GET /operations/new
  def new
    @operation = Operation.new
    @samples = Sample.all
  end

  # GET /operations/1/edit
  def edit
    @samples = Sample.all
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to @operation, notice: 'La Operación se creo con exito' }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to @operation, notice: 'La Operación se actulizo con exito' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to operations_url, notice: 'La operacion se eleminó exitosamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_params
      params.require(:operation).permit(:sample1, :sample2, :kleene)
    end
    ##
    # Metodo para la operacion union
    def unir(lenguaje1, lenguaje2)
      uno = lenguaje1.split(',')
      dos = lenguaje2.split(',')
      arreglo = uno | dos
      resultado = ''
      if ((uno - dos) == uno) && ((dos - uno) == dos)
        resultado = "{/}"
      else
        arreglo.each do |x|
          resultado += (x + ',')
        end
        resultado[-1] = ''
        resultado = "{#{resultado}}"
      end
    end
    ##
    # metodo para la interseccion
    def interseccion(lenguaje1, lenguaje2)
      uno = lenguaje1.split(',')
      dos = lenguaje2.split(',')
      arreglo = uno & dos
      resultado = ''
      if arreglo.length == 0
        resultado = "{/}"
      else
        arreglo.each do |x|
          resultado += (x + ',')
        end
        resultado[-1] = ''
        resultado = "{#{resultado}}"
      end
    end
    ##
    # metodo que ejecuta la estrella de kleene
    def estrella(lenguaje, veces)
      if veces == 1
        mensaje = "{ [ / ] }"
      else
        mensaje = "{ "
        veces.times do |x| 
          case x
          when 0 then mensaje += "[ / ]"
          when 1 then mensaje += ",[#{lenguaje}]"
          when 2 then 
            #concatena lenguaje con si mismo
            @ultimo = concatenar(lenguaje, lenguaje)
            mensaje += (',' + '[ ' + @ultimo + " ]")
          else
            #concatena el paso anterior con lenguaje
            @ultimo = concatenar(@ultimo, lenguaje)
            mensaje += (',' + '[ ' + @ultimo + " ]")
          end #cierra case
        end #cierra ciclo veces
        mensaje += " }"
      end #cierra if
    end
    ##
    # concatena dos lenguajes y retorna el resultado
    def concatenar(lenguaje1, lenguaje2)
      uno = lenguaje1.split(',')
      dos = lenguaje2.split(',')
      resultado = ''
      # concatenando ambos lenguajes
      uno.each do |x|
        dos.each do |y|
          resultado += (x + y + ',')
        end
      end
        #borra el ultimo caracter
        resultado[-1] = ''
      #retorna
      resultado
    end

    ##
    # El metodo Restar permite hacer la sustraccion entre lenguajes
    def restar(lenguaje1, lenguaje2)
      uno = lenguaje1.split(',')
      dos = lenguaje2.split(',')
      resultado = '{'
      # comparando que no se repitan elementos
      uno.each do |x|
        duplicado = false
        dos.each do |y|
          if x==y
            duplicado = true
          end
        end #cierra dos do
        # si no esta duplicado
        unless duplicado
          resultado += (x + ',')
        end
      end #cierra uno do
      if resultado == '{'
        resultado = '{/}'
      else
        resultado[-1] = '}'
      end
      #return
      resultado
    end

    ##
    # metodo para contar los elementos
    def cuenta(elemento)
        arreglo = elemento.split(',')
        arreglo.length
    end
end

AutomataOnRails/app/helpers/operations_helper.rb
module OperationsHelper
end

AutomataOnRails/app/views/operations/_form.html.erb
<%= form_for(@operation) do |f| %>
  <% if @operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
      <% @operation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="fila">
  <div class="small-12 medium-6 large-6 columnas">
    <%= f.label :sample1, "Lenguaje 1:" %>
    <%=f.select :sample1, options_from_collection_for_select(@samples, "id", "lenguaje").html_safe, multiple: true, class: 'blue-text', include_blank: "Elige un lenguaje"%>
  </div>
  <div class="small-12 medium-6 large-6 columnas">
    <%= f.label :sample2, "Lenguaje 2:" %>
    <%=f.select :sample2, options_from_collection_for_select(@samples, "id", "lenguaje").html_safe, multiple: true, class: 'blue-text', include_blank: "Elige un lenguaje"%>
  </div>
  <div class="small-12 medium-6 large-6 columnas">
    <%= f.label :kleene %>
    <p class="range-field">
      <%= f.range_field :kleene, in:1..10 %>
    </p>
  </div>
  <div class="small-12 medium-6 large-6 columnas right">
      <button class="btn-large waves-effect waves-light right" type="submit" name ="action">
        Guardar
        <i class="mdi-content-save"></i>
      </button>
    </div>
</div>
<% end %>

AutomataOnRails/app/views/operations/edit.html.erb
<h1>Editar Operación</h1>

<%= render 'form' %>

<div class="fila centrado center-align">
	<%= link_to @operation do%>
		<b>
			<i class="fa fa-eye"></i>
			Ver
		</b>
	<% end %> |
	<%= link_to operations_path do%>
		<b>
			<i class="fa fa-arrow-left"></i>
			Historial
		</b>
	<% end %>
</div>

AutomataOnRails/app/views/operations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card-panel fila centrado">
  <h1>Listado de operaciones</h1>

  <table class="centered bordered hoverable responsive-table">
    <thead>
      <tr>
        <th>Alfabeto1</th>
        <th>Lenguaje1</th>
        <th>Alfabeto2</th>
        <th>Lenguaje2</th>
        <th>Kleene</th>
        <th colspan="3">Opciones</th>
      </tr>
    </thead>

    <tbody>
      <% @operations.each do |operation| %>
        <tr>
          <%ver = Sample.find(operation.sample1)%>
          <td><%= ver.alfabeto %></td>
          <td><%= ver.lenguaje %></td>
          <%ver = Sample.find(operation.sample2)%>
          <td><%= ver.alfabeto %></td>
          <td><%= ver.lenguaje %></td>
          <td>Iteraciones: <%= operation.kleene %></td>
          <td><%= link_to operation do%>
              <b>
                <i class="fa fa-eye"></i>
                Ver
              </b>
            <% end %></td>
          <td><%= link_to edit_operation_path(operation) do%> 
                <b>
                  <i class="mdi-editor-mode-edit"></i>
                  Editar
                </b>
              <% end %></td>
          <td><%= link_to operation, method: :delete, data: { confirm: '¿Esta seguro que decea borrar este elemento?' } do%>
                <b>
                  <i class="mdi-action-delete"></i>
                  Borrar
                </b>
              <% end %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to new_operation_path, 'class' => 'btn-flat btn waves-effect waves-light blue accent-2 white-text right' do %>
    <i class="mdi-content-add"></i>Nuevo
  <% end %>
</div>

AutomataOnRails/app/views/operations/new.html.erb
<h1>Nueva Operación</h1>

<%= render 'form' %>

<div class="fila centrado center-align">
	<%= link_to operations_path do%>
		<b>
			<i class="fa fa-arrow-left"></i>
			Historial
		</b>
	<% end %>
</div>

AutomataOnRails/app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>
<div class="card fila centrado blue-grey darken-1 white-text tarjeta">
	<p class="card-title">Operaciones para:</p>
	<div class="card-content">
		<div class="card-panel small-12 medium-6 large-6 columnas blue-text">
			<p>
			  <h4>Elemento 1:</h4>
			  	<p>
					Alfabeto: <b>{<%= @elemento1.alfabeto%>}</b>
				</p>
				<p>
					Lenguaje: <b>{<%= @elemento1.lenguaje%>} (L1)</b>
				</p>
			</p>			
		</div>
		<div class="card-panel small-12 medium-6 large-6 columnas blue-text">
			<p>
			  <h4>Elemento 2:</h4>
			  	<p>
					Alfabeto: <b>{<%= @elemento2.alfabeto%>}</b>
				</p>
				<p>
					Lenguaje:<b>{<%= @elemento2.lenguaje%>} (L2)</b>
				</p>
			</p>
		</div>
		<div class="fila centrado">
			<div class="small-12 columna">
			  <ul class="tabs">
			    <li class="tab blue-grey darken-1 small-3 columnas">
			    	<a class="truncate purple-text text-lighten-4" href="#union">
			    		<span class="fa-stack fa-lg blue-text">
						  <i class="fa fa-circle fa-stack-2x"></i>
						  <i class="fa fa-stack-1x fa-inverse">⋃</i>
						</span>
			    		<strong class="hide-on-med-and-down">Union</strong>
		    		</a>
		    	</li>
		    	<li class="tab blue-grey darken-1 small-3 columnas">
			    	<a class="truncate purple-text text-lighten-4" href="#inter">
			    		<span class="fa-stack fa-lg blue-text">
						  <i class="fa fa-circle fa-stack-2x"></i>
						  <i class="fa fa-stack-1x fa-inverse">⋂</i>
						</span>
			    		<strong class="hide-on-med-and-down">Intersección</strong>
			    	</a>
		    	</li>
			    <li class="tab blue-grey darken-1 small-3 columnas">
					<a class="truncate purple-text text-lighten-4" href="#concatenacion">
						<span class="fa-stack fa-lg blue-text">
						  <i class="fa fa-circle fa-stack-2x"></i>
						  <i class="fa fa-stack-1x fa-inverse">·</i>
						</span>
			    		<strong class="hide-on-med-and-down">Concatenación</strong>
					</a>
				</li>
			    <li class="tab blue-grey darken-1 small-3 columnas">
			    	<a class="truncate purple-text text-lighten-4" href="#kleene">
			    		<span class="fa-stack fa-lg blue-text">
						  <i class="fa fa-circle fa-stack-2x"></i>
						  <i class="fa fa-stack-1x fa-inverse">*</i>
						</span>
			    		<strong class="hide-on-med-and-down">Estrella de Kleene</strong>
			    		
			    	</a>
		    	</li>
		    	<li class="tab blue-grey darken-1 small-3 columnas">
			    	<a class="truncate purple-text text-lighten-4" href="#resta">
			    		<span class="fa-stack fa-lg blue-text">
						  <i class="fa fa-circle fa-stack-2x"></i>
						  <i class="fa fa-stack-1x fa-inverse">-</i>
						</span>
			    		<strong class="hide-on-med-and-down">Resta</strong>
			    	</a>
		    	</li>
			  </ul>
			</div>
			<div class="fila">
				<div id="union" class="small-12 columna center-align desborde-x ajustado">
					<h4 class="subtitulo">La union de los lenguajes:</h4>
					<p>L1 ⋃ L2: <b><%= @union%></b></p>
					<p>L2 ⋃ L1: <b><%= @union%></b></p>
				</div>
				<div id="inter" class="small-12 columna center-align desborde-x ajustado">
					<h4 class="subtitulo">La Intersección de los lenguajes:</h4>
					<p>L1 ⋂ L2: <b><%= @inter%></b></p>
					<p>L2 ⋂ L1: <b><%= @inter%></b></p>
				</div>
				<div id="concatenacion" class="small-12 columna center-align desborde-x ajustado">
					<h4 class="subtitulo">La concatenación de los lenguajes:</h4>
					<p>L1 · L2: <b>{<%= @concat1%>}</b></p>
					<p>L2 · L1: <b>{<%= @concat2%>}</b></p>
				</div>
				<div id="kleene" class="small-12 columna center-align desborde-x ajustado">
					<h4 class="subtitulo">La Estrella de Kleene de los lenguajes:</h4>
					<p>
					  <strong>Numero de Interaciónes: </strong>
					  <%= @operation.kleene %>
					</p><br>
					<p>L1*: <b><%= @estrella1%></b></p>
					<p>
					  <strong>Numero de Elementos: </strong>
					  <%= @tamE1 %>
					</p><br>
					<p>L2*: <b><%= @estrella2%></b></p>
					<p>
					  <strong>Numero de Elementos: </strong>
					  <%= @tamE2 %>
					</p>
				</div>
				<div id="resta" class="small-12 columna center-align desborde-x ajustado">
					<h4 class="subtitulo">La resta de los lenguajes:</h4>
					<p>L1 - L2: <b><%= @resta1%></b></p>
					<p>L2 - L1: <b><%= @resta2%></b></p>
				</div>
			</div>
		</div>
	</div>
	<div class="card-action center-align">
		<%= link_to edit_operation_path(@operation) do%> 
                <b>
                  <i class="mdi-editor-mode-edit"></i>
                  Editar
                </b>
              <% end %>
		<%= link_to operations_path do%>
			<b>
				<i class="fa fa-arrow-left"></i>
				Historial
			</b>
		<% end %>		
	</div>
</div>