AutomataOnRails/config/routes.rb
Rails.application.routes.draw do
  root 'inicio#index'

  resources :operations

  resources :samples

end

AutomataOnRails/app/models/sample.rb
	class Sample < ActiveRecord::Base
		validates :alfabeto, presence: true
		validates :lenguaje, presence: true, uniqueness: true
	end

AutomataOnRails/app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)
    @sample.alfabeto = limpiar(@sample.alfabeto)
    @sample.lenguaje = limpiar(@sample.lenguaje)
    if (lenguajeCorrecto(@sample.alfabeto, @sample.lenguaje) == "Correcto")
      respond_to do |format|
        if @sample.save
          format.html { redirect_to @sample, notice: 'Los datos se crearon exitosamente' }
          format.json { render :show, status: :created, location: @sample }
        else
          format.html { render :new }
          format.json { render json: @sample.errors, status: :unprocessable_entity }
        end #cierra if
      end #cierra respod_to
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end #cierra respond
    end #cierra if principal
  end #cierra create

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    @sample.alfabeto = limpiar(@sample.alfabeto)
    @sample.lenguaje = limpiar(@sample.lenguaje)
    if (lenguajeCorrecto(@sample.alfabeto, @sample.lenguaje) == "Correcto")
      respond_to do |format|
        if @sample.update(sample_params)
          format.html { redirect_to @sample, notice: 'Los datos se crearon exitosamente' }
          format.json { render :show, status: :created, location: @sample }
        else
          format.html { render :new }
          format.json { render json: @sample.errors, status: :unprocessable_entity }
        end #cierra if
      end #cierra respod_to
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end #cierra respond
    end #cierra if 
  end #cierra update

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Los datos se eliminaron exitosamente' }
      format.json { head :no_content }
    end
  end

  protected
  # Verifica que el lenguaje sea coerente con el alfabeto
  def lenguajeCorrecto(alfabeto, lenguaje)
    alfa = alfabeto.split(',')
    leng = lenguaje.split(',')
    todos = 0
    # cada elemento del lenguaje es un elemento x
    leng.each do |x|
      coinseden = 0
      #cada caracter del un elemento x es i
      x.each_char do |i|
        # cada caracter del alfabeto es j
        alfa.each do |j|
          if i==j #si la j es igual que un elemento de i
            coinseden = coinseden + 1
            break
          end #cierra if
        end #cierra alfa.each
      end #cierra x.each_char
      mensaje = ''
      if coinseden==x.length
        todos = todos + 1
      end #cierra if
    end #cierra leng.each
      #return
      if todos==leng.length
          mensaje = "Correcto"
      else
        mensaje = "Incorrecto"
      end
  end #cierra metodo lenguajeCorrecto
  def limpiar(elemento)
    arreglo = elemento.split(',')
    arreglo = arreglo.uniq
    cadena = ''
    arreglo.each do |x|
      cadena += (x + ",")  
    end #cierra do 
    cadena[-1] = ''
    cadena
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:alfabeto, :lenguaje)
    end
end

AutomataOnRails/app/helpers/samples_helper.rb
module SamplesHelper
end

AutomataOnRails/app/views/samples/_form.html.erb
<div class="container card-panel centrado">  
  <%= form_for(@sample) do |f| %>
    <% if @sample.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@sample.errors.count, "error") %> Esta información no pudo ser guardada:</h2>

        <ul>
        <% @sample.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <div class="fila">
    <div class="input-field small-12 medium-6 large-6 columnas">
      <%= f.label :alfabeto, "Alfabeto :" %>
      <%= f.text_field :alfabeto, :required => true, :pattern => "[0-9a-zA-Z]{1}([,][0-9a-zA-Z])*", :title => "Ingrese un alfabeto valido", :class => "validate" %>
    </div>
    <div class="input-field small-12 medium-6 large-6 columnas">
      <%= f.label :lenguaje, "Lenguaje :" %>
      <%= f.text_field :lenguaje, :required => true, :pattern => "[0-9a-zA-Z]+([,][0-9a-zA-Z]+)*", :title => "Ingrese un lenguaje valido", :class => "validate" %>
    </div>
  </div>
  <div class="fila">
    <div class="small-12 medium-6 large-6 columnas right">
      <button class="btn-large waves-effect waves-light right" type="submit" name ="action">
        Guardar
        <i class="mdi-content-save"></i>
      </button>
    </div>
  </div>
  <!--
    <div class="actions">
      <%= f.submit %>
    </div>
  -->
  <% end %>
</div>

AutomataOnRails/app/views/samples/edit.html.erb
<h1>Editar Alfabeto y/o Lenguaje</h1>

<%= render 'form' %>
<div class="fila centrado center-align">
	<%= link_to @sample do%>
		<b>
			<i class="fa fa-eye"></i>
			Ver
		</b>
	<% end %> |
	<%= link_to samples_path do%>
		<b>
			<i class="fa fa-arrow-left"></i>
			Lenguajes
		</b>
	<% end %>
</div>

AutomataOnRails/app/views/samples/index.html.erb
<p id="notice"><%= notice %></p>

<div class="card-panel fila centrado">
  <h1>Listado: Alfabetos y lenguajes</h1>

  <table class="centered bordered hoverable responsive-table">
    <thead>
      <tr>
        <th>Alfabeto</th>
        <th>Lenguaje</th>
        <th colspan="2">Opciones</th>
      </tr>
    </thead>

    <tbody>
      <% @samples.each do |sample| %>
        <tr>
          <td><%= sample.alfabeto %></td>
          <td><%= sample.lenguaje %></td>
          <td><%= link_to edit_sample_path(sample.id) do%> 
                <b>
                  <i class="mdi-editor-mode-edit"></i>
                  Editar
                </b>
              <% end %>
          </td>
          <td><%= link_to sample, method: :delete, data: { confirm: '¿Esta seguro que decea borrar este elemento?' } do%>
              <b>
                <i class="mdi-action-delete"></i>
                Borrar
              </b>
            <% end %> 
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>
  <%= link_to new_sample_path, 'class' => 'btn-flat btn waves-effect waves-light blue accent-2 white-text right' do %>
    <i class="mdi-content-add"></i>Nuevo
  <% end %>
  <%unless @samples.count<2%>
    <%= link_to new_operation_path, 'class' => 'btn-flat btn waves-effect waves-light deep-purple accent-2 white-text right' do %>
      <i class="fa fa-magic"></i>Operaciones
    <% end %>
  <% end %>
</div>

AutomataOnRails/app/views/samples/new.html.erb
<h1>Nuevo Alfabeto Y Lenguaje</h1>

<%= render 'form' %>

<div class="fila centrado center-align">
	<%= link_to samples_path do%>
		<b>
			<i class="fa fa-arrow-left"></i>
			Lenguajes
		</b>
	<% end %>
</div>

AutomataOnRails/app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

 <div class="fila centrado center-align">
	<div class="small-12 medium-10 large-8">
	  <div class="card blue-grey lighten-1">
	    <div class="card-content white-text">
	      <span class="card-title">Alfabeto Y Lenguaje</span>
			<p>
			  <strong>Alfabeto:</strong>
			  <%= @sample.alfabeto %>
			</p>

			<p>
			  <strong>Lenguaje:</strong>
			  <%= @sample.lenguaje %>
			</p>
	    </div>
	    <div class="card-action">
			<%= link_to edit_sample_path(@sample) do%> 
				<b>
					<i class="mdi-editor-mode-edit"></i>
					Editar
				</b>
			<% end %>
			<%= link_to samples_path do%>
				<b>
					<i class="fa fa-arrow-left"></i>
					Lenguajes
				</b>
			<% end %>
	    </div>
	  </div>
	</div>
</div>